import App from './App'
import { createSSRApp } from 'vue'
import { createPinia } from 'pinia'
import DebugPageNav from './components/DebugPageNav/index.uvue'
import AppIcon from './components/AppIcon/index.uvue'

export function createApp() {
  const app = createSSRApp(App)
  app.use(createPinia())
  app.component('DebugPageNav', DebugPageNav)
  app.component('AppIcon', AppIcon)
  return { app }
}
